// <auto-generated />
using System;
using IntegrationLibrary.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationLibrary.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    partial class IntegrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IntegrationLibrary.BloodBank.BloodBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdminPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequently")
                        .HasColumnType("int");

                    b.Property<string>("GetBloodTypeAndAmountAvailability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GetBloodTypeAvailability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDummyPassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReportTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BloodBanks");
                });

            modelBuilder.Entity("IntegrationLibrary.News.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("IntegrationLibrary.Tender.Tender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TenderWinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenderWinnerId");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("IntegrationLibrary.Tender.TenderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int?>("TenderId")
                        .HasColumnType("int");

                    b.Property<int?>("TenderOfferId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.HasIndex("TenderOfferId");

                    b.ToTable("TenderItem");
                });

            modelBuilder.Entity("IntegrationLibrary.Tender.TenderOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OfferorId")
                        .HasColumnType("int");

                    b.Property<int?>("TenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfferorId");

                    b.HasIndex("TenderId");

                    b.ToTable("TenderOffer");
                });

            modelBuilder.Entity("IntegrationLibrary.Tender.Tender", b =>
                {
                    b.HasOne("IntegrationLibrary.Tender.TenderOffer", "TenderWinner")
                        .WithMany()
                        .HasForeignKey("TenderWinnerId");

                    b.Navigation("TenderWinner");
                });

            modelBuilder.Entity("IntegrationLibrary.Tender.TenderItem", b =>
                {
                    b.HasOne("IntegrationLibrary.Tender.Tender", null)
                        .WithMany("Items")
                        .HasForeignKey("TenderId");

                    b.HasOne("IntegrationLibrary.Tender.TenderOffer", null)
                        .WithMany("Items")
                        .HasForeignKey("TenderOfferId");

                    b.OwnsOne("IntegrationLibrary.Tender.Money", "Money", b1 =>
                        {
                            b1.Property<int>("TenderItemId")
                                .HasColumnType("int");

                            b1.Property<double>("Amount")
                                .HasColumnType("float");

                            b1.Property<int>("Currency")
                                .HasColumnType("int");

                            b1.HasKey("TenderItemId");

                            b1.ToTable("TenderItem");

                            b1.WithOwner()
                                .HasForeignKey("TenderItemId");
                        });

                    b.Navigation("Money");
                });

            modelBuilder.Entity("IntegrationLibrary.Tender.TenderOffer", b =>
                {
                    b.HasOne("IntegrationLibrary.BloodBank.BloodBank", "Offeror")
                        .WithMany()
                        .HasForeignKey("OfferorId");

                    b.HasOne("IntegrationLibrary.Tender.Tender", null)
                        .WithMany("Offers")
                        .HasForeignKey("TenderId");

                    b.Navigation("Offeror");
                });

            modelBuilder.Entity("IntegrationLibrary.Tender.Tender", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("IntegrationLibrary.Tender.TenderOffer", b =>
                {
                    b.Navigation("Items");

            modelBuilder.Entity("IntegrationLibrary.BloodBank.BloodBank", b =>
                {
                    b.OwnsOne("IntegrationLibrary.BloodBank.MonthlyTransfer", "MonthlyTransfer", b1 =>
                        {
                            b1.Property<int>("BloodBankId")
                                .HasColumnType("int");

                            b1.Property<int>("ABMinus")
                                .HasColumnType("int");

                            b1.Property<int>("ABPlus")
                                .HasColumnType("int");

                            b1.Property<int>("AMinus")
                                .HasColumnType("int");

                            b1.Property<int>("APlus")
                                .HasColumnType("int");

                            b1.Property<int>("BMinus")
                                .HasColumnType("int");

                            b1.Property<int>("BPlus")
                                .HasColumnType("int");

                            b1.Property<DateTime>("DateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int>("OMinus")
                                .HasColumnType("int");

                            b1.Property<int>("OPlus")
                                .HasColumnType("int");

                            b1.HasKey("BloodBankId");

                            b1.ToTable("BloodBanks");

                            b1.WithOwner()
                                .HasForeignKey("BloodBankId");
                        });

                    b.Navigation("MonthlyTransfer");
                });
#pragma warning restore 612, 618
        }
    }
}
